# Generated by Django 4.0.5 on 2022-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_advertisement_alter_category_description_delete_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='publicated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
